import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:path/path.dart' as p;
import 'package:shared_preferences/shared_preferences.dart';

import 'package:nex_client/app.dart';
import 'package:nex_client/l10n/app_localizations.dart';
import 'package:nex_client/platform/ai_provider.dart';
import 'package:nex_client/platform/backup_policy.dart';
import 'package:nex_client/platform/nex_preferences.dart';
import 'package:nex_client/platform/nex_services.dart';
import 'package:nex_client/screens/timeline_screen.dart';
import 'package:nex_client/widgets/nex_banner.dart';

import 'support/in_process_db.dart';

/// The daily recap is generated by whatever provider the user configured, and
/// the provider can always fail — no signal, an expired key, an empty reply.
/// What is tested here is who gets told.
///
/// Nothing in this file reaches a network: `flutter_test` answers every
/// request with a 400, which is exactly the failure being modelled.
void main() {
  late Directory tmp;
  late NexServices services;
  late NexPreferences preferences;

  setUp(() async {
    SharedPreferences.setMockInitialValues({});
    tmp = Directory.systemTemp.createTempSync('nex_recap_');
    final dbPath = p.join(tmp.path, 'nex.sqlite');
    final mediaDir = p.join(tmp.path, 'media');
    final backupDir = p.join(tmp.path, 'backups');
    Directory(mediaDir).createSync(recursive: true);
    Directory(backupDir).createSync(recursive: true);
    preferences = await NexPreferences.load();
    services = NexServices.forTest(
      worker: InProcessDb(dbPath: dbPath, deviceId: 'test'),
      deviceId: 'test',
      preferences: preferences,
      backupPolicy: BackupPolicy(await SharedPreferences.getInstance()),
      dbPath: dbPath,
      mediaDir: mediaDir,
      backupDir: backupDir,
    );
    await preferences.completeOnboarding();
    await preferences.completeTour();
    // A configured provider, which is what puts the recap card on screen at
    // all. The key is never used — the request fails before it matters.
    await preferences.setAiEnabled(true);
    await preferences.setAiProvider(
      const AiProviderConfig(provider: AiProvider.openai, apiKey: 'k'),
    );
    await services.captureText('something worth summarising');
    await services.refreshTimeline();
  });

  tearDown(() async {
    nexHideBanner();
    await services.dispose();
    if (tmp.existsSync()) tmp.deleteSync(recursive: true);
  });

  testWidgets('a recap nobody asked for fails quietly; a tap is answered', (
    tester,
  ) async {
    await tester.pumpWidget(
      NexApp(services: services, preferences: preferences),
    );
    await tester.pumpAndSettle();

    final l10n = AppLocalizations.of(
      tester.element(find.byType(TimelineScreen)),
    );

    // What makes the assertion below mean something. The launch attempt is
    // fired by the timeline stream delivering its first non-empty list, so a
    // note on screen is the trigger condition having been met.
    expect(find.text('something worth summarising'), findsOneWidget);

    // The launch attempt. It runs once, by itself, the first time the timeline
    // delivers any notes — so it lands seconds after start, over whatever the
    // user has opened by then. The screenshot in the report was of this banner
    // sitting over the settings sheet, about a card the user had not touched.
    //
    // The card's own rule says why that is wrong: the recap is additive
    // chrome, never a reason to put an error on the screen. A failure with no
    // tap behind it leaves the old line and says nothing.
    expect(
      find.text(l10n.recapRefreshFailed),
      findsNothing,
      reason: 'nobody asked for this one',
    );

    // The other half, which must keep working: a tap that visibly does
    // nothing is what a broken button looks like, so the tap is answered.
    // It also closes the other way out of the assertion above: this proves
    // the whole path is live — a provider configured, the card on screen, the
    // request made, the failure noticed, the banner raised. The launch
    // attempt runs the same method against the same source, so silence there
    // is the rule being applied and not the code never running.
    await tester.tap(find.byTooltip(l10n.aiDaySummaryRefresh));
    await tester.pumpAndSettle();

    expect(find.text(l10n.recapRefreshFailed), findsOneWidget);
  });
}
