import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:path/path.dart' as p;
import 'package:shared_preferences/shared_preferences.dart';

import 'package:nex_client/app.dart';
import 'package:nex_client/l10n/app_localizations.dart';
import 'package:nex_client/platform/ai_provider.dart';
import 'package:nex_client/platform/backup_policy.dart';
import 'package:nex_client/platform/nex_preferences.dart';
import 'package:nex_client/platform/nex_services.dart';
import 'package:nex_client/screens/timeline_screen.dart';
import 'package:nex_client/widgets/nex_banner.dart';

import 'support/in_process_db.dart';

/// The daily recap is generated by whatever provider the user configured, and
/// the provider can always fail — no signal, an expired key, an empty reply.
/// What is tested here is who gets told.
///
/// Nothing in this file reaches a network: `flutter_test` answers every
/// request with a 400, which is exactly the failure being modelled.
void main() {
  late Directory tmp;
  late NexServices services;
  late NexPreferences preferences;

  setUp(() async {
    SharedPreferences.setMockInitialValues({});
    tmp = Directory.systemTemp.createTempSync('nex_recap_');
    final dbPath = p.join(tmp.path, 'nex.sqlite');
    final mediaDir = p.join(tmp.path, 'media');
    final backupDir = p.join(tmp.path, 'backups');
    Directory(mediaDir).createSync(recursive: true);
    Directory(backupDir).createSync(recursive: true);
    preferences = await NexPreferences.load();
    services = NexServices.forTest(
      worker: InProcessDb(dbPath: dbPath, deviceId: 'test'),
      deviceId: 'test',
      preferences: preferences,
      backupPolicy: BackupPolicy(await SharedPreferences.getInstance()),
      dbPath: dbPath,
      mediaDir: mediaDir,
      backupDir: backupDir,
    );
    await preferences.completeOnboarding();
    await preferences.completeTour();
    // A configured provider, which is what puts the recap card on screen at
    // all. The key is never used — the request fails before it matters.
    await preferences.setAiEnabled(true);
    await preferences.setAiProvider(
      const AiProviderConfig(provider: AiProvider.openai, apiKey: 'k'),
    );
    await services.captureText('something worth summarising');
    await services.refreshTimeline();
  });

  tearDown(() async {
    nexHideBanner();
    await services.dispose();
    if (tmp.existsSync()) tmp.deleteSync(recursive: true);
  });

  testWidgets('a recap nobody asked for fails quietly; a tap is answered', (
    tester,
  ) async {
    await tester.pumpWidget(
      NexApp(services: services, preferences: preferences),
    );
    // Pumped by hand rather than settled, and this is the whole trick of the
    // file. A banner lives 3400ms and then takes itself away; the brief's
    // border beam schedules frames for four laps of 2200ms. `pumpAndSettle`
    // pumps *while frames are scheduled*, so it runs the beam out over eight
    // and a half seconds of test time — past the life of any banner raised
    // along the way. Five rounds were spent looking for a banner that had
    // been shown and swept up before the assertion ran.
    for (var i = 0; i < 10; i++) {
      await tester.pump(const Duration(milliseconds: 100));
    }

    final l10n = AppLocalizations.of(
      tester.element(find.byType(TimelineScreen)),
    );

    // What makes the assertions below mean something. The launch attempt is
    // fired by the timeline stream delivering its first non-empty list, so a
    // note on screen is the trigger condition having been met.
    expect(find.text('something worth summarising'), findsOneWidget);

    // And that the attempt is over rather than still running: the card is
    // dimmed while a brief is being written, and a refresh asked for while
    // one is in flight is declined by design. This is that state, read from
    // outside — `AnimatedOpacity` carries the target, not the current value.
    double writing() => tester
        .widget<AnimatedOpacity>(
          find.descendant(
            of: find.byKey(const ValueKey('timeline-recap')),
            matching: find.byType(AnimatedOpacity),
          ),
        )
        .opacity;
    expect(writing(), 1.0, reason: 'the launch attempt is still in flight');

    // So the launch attempt ran, failed, and said nothing — with a second to
    // spare on the clock, which is what makes this an assertion rather than a
    // race the banner always loses. It lands seconds after start, over
    // whatever the user has opened by then: the screenshot in the report was
    // of this banner sitting over the settings sheet, about a card nobody had
    // touched.
    //
    // The card's own rule says why that is wrong: the recap is additive
    // chrome, never a reason to put an error on the screen. A failure with no
    // tap behind it leaves the old line and says nothing.
    expect(
      find.text(l10n.recapRefreshFailed),
      findsNothing,
      reason: 'nobody asked for this one',
    );

    // The other half, which must keep working: a gesture that visibly does
    // nothing is what a broken control looks like, so the ask is answered.
    // A `RefreshIndicator` is attached, and only because there is a brief to
    // rewrite — `_wrapInRefresh` leaves it off otherwise, so that a pull with
    // nothing to refresh is not a gesture that silently does nothing.
    final indicator = tester.widget<RefreshIndicator>(
      find.byType(RefreshIndicator),
    );

    // Asked for by calling the callback the indicator calls, not by
    // simulating a finger: a simulated pull tests Flutter's gesture
    // arithmetic — how much overscroll carries `dragDetails`, and that the
    // arming threshold is a quarter of the viewport rather than a fixed
    // distance — and none of that says whether this app raises the banner.
    await indicator.onRefresh();
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 400));

    expect(find.text(l10n.recapRefreshFailed), findsOneWidget);

    // And it goes by itself — nothing here has to be acknowledged. Settled
    // at the end rather than the start, which is the same fact about this
    // screen read the other way round: now that the banner is the thing being
    // waited out, running the beam to a stop is exactly what is wanted.
    await tester.pump(const Duration(seconds: 4));
    await tester.pumpAndSettle();
    expect(find.text(l10n.recapRefreshFailed), findsNothing);
  });
}
