#!/usr/bin/env python3
"""Builds the alternative launcher icons from one square picture each.

Settings offers six icons: the app's own (the usual ic_launcher resources,
not touched here) and five alternatives. Put five pictures in
apps/client/app_icons/ named alt1.png … alt5.png, then run from the repo root:

    python3 tools/generate_app_icons.py

Each source must be a square PNG, ideally 1024×1024, filling the whole square
(no transparent corners): Android cuts the launcher shape out of it itself.
Keep anything that must be seen — a logo, a letter — inside the central
circle about 620 px across; the outer ~170 px on each side can be hidden by
the launcher's mask or used for its parallax.

For every source this writes:

- res/mipmap-<density>/ic_launcher_altN_layer.png — the adaptive-icon layer
  (108 dp: 108/162/216/324/432 px), which Android 8+ masks into its shape;
- res/mipmap-anydpi-v26/ic_launcher_altN.xml — the adaptive icon itself;
- res/mipmap-<density>/ic_launcher_altN.png — a rounded square for Android 7;
- assets/app_icons/altN.png — the 192 px preview shown in Settings.

It also refreshes assets/app_icons/default.png from the current app icon.
Requires Pillow (pip install pillow).
"""

from pathlib import Path
import sys

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
CLIENT = ROOT / "apps" / "client"
SOURCES = CLIENT / "app_icons"
RES = CLIENT / "android" / "app" / "src" / "main" / "res"
PREVIEWS = CLIENT / "assets" / "app_icons"
DENSITIES = {"mdpi": 1, "hdpi": 1.5, "xhdpi": 2, "xxhdpi": 3, "xxxhdpi": 4}
COUNT = 5

ADAPTIVE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/generate_app_icons.py from app_icons/alt{n}.png. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/ic_launcher_alt{n}_layer" />
    <foreground android:drawable="@android:color/transparent" />
</adaptive-icon>
"""


def visible(art: Image.Image) -> Image.Image:
    """The part a launcher actually shows: the central 72 of 108 dp."""
    side = art.width
    inset = round(side * 18 / 108)
    return art.crop((inset, inset, side - inset, side - inset))


def rounded(image: Image.Image, radius: float) -> Image.Image:
    mask = Image.new("L", image.size, 0)
    ImageDraw.Draw(mask).rounded_rectangle(
        (0, 0, image.width - 1, image.height - 1),
        radius=round(image.width * radius),
        fill=255,
    )
    out = image.copy()
    out.putalpha(mask)
    return out


def build(n: int) -> None:
    source = SOURCES / f"alt{n}.png"
    art = Image.open(source).convert("RGBA")
    if art.width != art.height:
        sys.exit(f"{source} must be square, is {art.width}×{art.height}")
    art = art.resize((1024, 1024), Image.LANCZOS)
    for density, scale in DENSITIES.items():
        folder = RES / f"mipmap-{density}"
        folder.mkdir(parents=True, exist_ok=True)
        layer = round(108 * scale)
        art.resize((layer, layer), Image.LANCZOS).save(
            folder / f"ic_launcher_alt{n}_layer.png", optimize=True
        )
        legacy = round(48 * scale)
        rounded(visible(art).resize((legacy, legacy), Image.LANCZOS), 0.22).save(
            folder / f"ic_launcher_alt{n}.png", optimize=True
        )
    anydpi = RES / "mipmap-anydpi-v26"
    anydpi.mkdir(parents=True, exist_ok=True)
    (anydpi / f"ic_launcher_alt{n}.xml").write_text(ADAPTIVE.format(n=n))
    PREVIEWS.mkdir(parents=True, exist_ok=True)
    visible(art).resize((192, 192), Image.LANCZOS).save(
        PREVIEWS / f"alt{n}.png", optimize=True
    )
    print(f"alt{n}: done")


def main() -> None:
    missing = [n for n in range(1, COUNT + 1) if not (SOURCES / f"alt{n}.png").exists()]
    if missing:
        sys.exit(f"missing sources in {SOURCES}: " + ", ".join(f"alt{n}.png" for n in missing))
    for n in range(1, COUNT + 1):
        build(n)
    current = Image.open(RES / "mipmap-xxxhdpi" / "ic_launcher.png").convert("RGBA")
    current.resize((192, 192), Image.LANCZOS).save(PREVIEWS / "default.png", optimize=True)
    print("default preview: done")


if __name__ == "__main__":
    main()
